name: linter-flake8 check

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install flake8
      - name: Run linter
        run: |
          flake8 ./

